---
url: https://www.emfink.net # the base hostname & protocol for your site
baseurl: /lj-folio # the subpath of your site, e.g. /blog/
title: Eric M. Fink # the title of your site as you want it to appear on 'About' page and in header of other pages 
description:  # leave blank if you don't want to display a description 
last_updated: 22 August 2021 # leave blank if you don't want to display last updated

name: Eric M. Fink # site author name as you want it to appear on 'About' page and elsewhere 
# Replace the following with your contact information 
position: Associate Professor
institution: Elon Law School
street: 201 North Greene Street
city: Greensboro
state: North Carolina
zip: '27401'
email: efink@elon.edu
phone: 336-279-9334

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
anchorjs_version: "3.2.2"
